/**
 * Seed script — populates the database with realistic sample Vermont sightings.
 * Run with:  npm run seed   (from the server/ directory)
 *            npm run seed   (from the project root)
 */

import db from './database'

// Clear existing seed data so the script is safely re-runnable
db.prepare("DELETE FROM sightings WHERE id LIKE 'seed-%'").run()

const now = new Date()
const daysAgo = (n: number) => {
  const d = new Date(now)
  d.setDate(d.getDate() - n)
  return d.toISOString().split('T')[0]
}

const seedData = [
  {
    id: 'seed-001',
    sighting_date: daysAgo(3),
    sighting_time: '07:30',
    town: 'Burlington',
    state: 'Vermont',
    latitude: 44.4759,
    longitude: -73.2121,
    location_type: 'backyard',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['near_trash']),
    distance_ft: 30,
    human_food_present: 1,
    pets_present: 0,
    description: 'A large black bear was rummaging through my compost bin early this morning. It left when I turned on the porch light.',
    submitter_name: 'Sarah Chen',
    submitter_email: 'sarah@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-002',
    sighting_date: daysAgo(5),
    sighting_time: '14:15',
    town: 'Stowe',
    state: 'Vermont',
    latitude: 44.4654,
    longitude: -72.6874,
    location_type: 'trail',
    bear_count: 3,
    bear_type: 'mother_with_cubs',
    behaviors: JSON.stringify(['eating', 'calm']),
    distance_ft: 80,
    human_food_present: 0,
    pets_present: 0,
    description: 'Mother bear and two cubs foraging along the trail. They were completely unbothered and moved off into the woods after a few minutes.',
    submitter_name: 'Marcus Webb',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-003',
    sighting_date: daysAgo(7),
    sighting_time: '06:00',
    town: 'Montpelier',
    state: 'Vermont',
    latitude: 44.2601,
    longitude: -72.5754,
    location_type: 'neighborhood',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['crossing_road']),
    distance_ft: 50,
    human_food_present: 0,
    pets_present: 0,
    description: 'Bear crossed Elm Street heading toward the river. Early morning commute, very quick sighting.',
    submitter_name: 'Patricia Morse',
    submitter_email: 'pmorse@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'pending',
    reviewed_at: null,
  },
  {
    id: 'seed-004',
    sighting_date: daysAgo(10),
    sighting_time: '19:45',
    town: 'Brattleboro',
    state: 'Vermont',
    latitude: 42.8509,
    longitude: -72.5579,
    location_type: 'forest',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['calm', 'resting']),
    distance_ft: 120,
    human_food_present: 0,
    pets_present: 0,
    description: 'Bear resting at the base of a large oak tree. Observed for about 10 minutes before it moved deeper into the woods.',
    submitter_name: 'Daniel Forrest',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-005',
    sighting_date: daysAgo(12),
    sighting_time: '05:30',
    town: 'Middlebury',
    state: 'Vermont',
    latitude: 44.0154,
    longitude: -73.1673,
    location_type: 'farm',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['near_trash', 'eating']),
    distance_ft: 40,
    human_food_present: 1,
    pets_present: 1,
    description: 'Bear got into the chicken coop area. No chickens were harmed but the feed container was knocked over. Dogs were barking and seemed to scare it off.',
    submitter_name: 'Helen Trask',
    submitter_email: 'htrask@farmmail.com',
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-006',
    sighting_date: daysAgo(14),
    sighting_time: '08:20',
    town: 'Woodstock',
    state: 'Vermont',
    latitude: 43.6237,
    longitude: -72.5218,
    location_type: 'road',
    bear_count: 1,
    bear_type: 'unknown',
    behaviors: JSON.stringify(['crossing_road']),
    distance_ft: 20,
    human_food_present: 0,
    pets_present: 0,
    description: 'Bear ran across Route 4 in front of my car. I had to brake hard. It disappeared into the tree line on the south side.',
    submitter_name: 'James Aldrich',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'pending',
    reviewed_at: null,
  },
  {
    id: 'seed-007',
    sighting_date: daysAgo(16),
    sighting_time: '21:00',
    town: 'Manchester',
    state: 'Vermont',
    latitude: 43.1634,
    longitude: -73.0657,
    location_type: 'campsite',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['aggressive', 'near_trash']),
    distance_ft: 15,
    human_food_present: 1,
    pets_present: 0,
    description: 'Bear approached campsite and was acting aggressively toward our food storage. We made noise and it eventually left. Food had been improperly stored in a cooler outside.',
    submitter_name: 'Tori Nguyen',
    submitter_email: 'tnguyen@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'flagged',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-008',
    sighting_date: daysAgo(18),
    sighting_time: '09:10',
    town: 'St. Johnsbury',
    state: 'Vermont',
    latitude: 44.4193,
    longitude: -72.0188,
    location_type: 'backyard',
    bear_count: 1,
    bear_type: 'cub',
    behaviors: JSON.stringify(['climbing_tree', 'calm']),
    distance_ft: 60,
    human_food_present: 0,
    pets_present: 0,
    description: 'Spotted a cub climbing a large maple tree in the backyard. Did not see a mother bear but stayed inside as a precaution.',
    submitter_name: 'Robert Kline',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-009',
    sighting_date: daysAgo(20),
    sighting_time: '17:30',
    town: 'Bennington',
    state: 'Vermont',
    latitude: 42.8778,
    longitude: -73.1968,
    location_type: 'neighborhood',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['crossing_road', 'calm']),
    distance_ft: 35,
    human_food_present: 0,
    pets_present: 1,
    description: 'Bear walked calmly through the neighborhood in broad daylight. My neighbor\'s dog was going crazy. The bear seemed completely unbothered.',
    submitter_name: 'Cindy Larson',
    submitter_email: 'clarson@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'pending',
    reviewed_at: null,
  },
  {
    id: 'seed-010',
    sighting_date: daysAgo(22),
    sighting_time: '11:00',
    town: 'Rutland',
    state: 'Vermont',
    latitude: 43.6106,
    longitude: -72.9726,
    location_type: 'backyard',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['resting', 'calm']),
    distance_ft: 100,
    human_food_present: 0,
    pets_present: 0,
    description: 'Bear was lying in the shade at the far end of my yard for about 30 minutes during the midday heat. Just resting. Moved on without incident.',
    submitter_name: 'Alan Pierce',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-011',
    sighting_date: daysAgo(24),
    sighting_time: '15:45',
    town: 'Newport',
    state: 'Vermont',
    latitude: 44.9368,
    longitude: -72.2046,
    location_type: 'trail',
    bear_count: 3,
    bear_type: 'mother_with_cubs',
    behaviors: JSON.stringify(['eating', 'calm']),
    distance_ft: 150,
    human_food_present: 0,
    pets_present: 0,
    description: 'Mother and two cubs eating blueberries along the trail. We backed away slowly and gave them space. Absolutely beautiful sight.',
    submitter_name: 'Frances Bloom',
    submitter_email: 'fbloom@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-012',
    sighting_date: daysAgo(26),
    sighting_time: '06:45',
    town: 'Waterbury',
    state: 'Vermont',
    latitude: 44.3376,
    longitude: -72.7565,
    location_type: 'road',
    bear_count: 1,
    bear_type: 'unknown',
    behaviors: JSON.stringify(['crossing_road']),
    distance_ft: 25,
    human_food_present: 0,
    pets_present: 0,
    description: 'Quick sighting on Route 2 heading toward I-89 on-ramp. Bear crossed in front of me at dawn. No time to get a photo.',
    submitter_name: 'Greg Holt',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'pending',
    reviewed_at: null,
  },
  {
    id: 'seed-013',
    sighting_date: daysAgo(28),
    sighting_time: '08:00',
    town: 'Shelburne',
    state: 'Vermont',
    latitude: 44.3823,
    longitude: -73.2279,
    location_type: 'backyard',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['eating', 'near_trash']),
    distance_ft: 20,
    human_food_present: 1,
    pets_present: 0,
    description: 'Bear pulled down our bird feeders and ate all the sunflower seeds. This is the third time this month. Have now brought feeders inside.',
    submitter_name: 'Nancy Dubois',
    submitter_email: 'ndubois@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-014',
    sighting_date: daysAgo(30),
    sighting_time: '16:20',
    town: 'Morrisville',
    state: 'Vermont',
    latitude: 44.5598,
    longitude: -72.5979,
    location_type: 'forest',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['eating', 'calm']),
    distance_ft: 200,
    human_food_present: 0,
    pets_present: 0,
    description: 'Spotted a large bear in a clearing off the logging road, eating what appeared to be berries. Watched through binoculars from a safe distance.',
    submitter_name: 'Ted Russo',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-015',
    sighting_date: daysAgo(2),
    sighting_time: '22:10',
    town: 'Stowe',
    state: 'Vermont',
    latitude: 44.4701,
    longitude: -72.6820,
    location_type: 'backyard',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['near_trash']),
    distance_ft: 25,
    human_food_present: 1,
    pets_present: 0,
    description: 'Bear tipped over all three of our trash cans. Heard the noise from inside and saw it on the motion camera. Secured the cans the next morning.',
    submitter_name: 'Kim Patel',
    submitter_email: 'kpatel@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'pending',
    reviewed_at: null,
  },
  {
    id: 'seed-016',
    sighting_date: daysAgo(1),
    sighting_time: '07:00',
    town: 'Burlington',
    state: 'Vermont',
    latitude: 44.4820,
    longitude: -73.2050,
    location_type: 'neighborhood',
    bear_count: 2,
    bear_type: 'adult',
    behaviors: JSON.stringify(['crossing_road', 'calm']),
    distance_ft: 45,
    human_food_present: 0,
    pets_present: 0,
    description: 'Two adult bears, possibly a mating pair, walked through the South End neighborhood at dawn. Neighbors were watching from windows.',
    submitter_name: 'Oliver Grant',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'pending',
    reviewed_at: null,
  },
  {
    id: 'seed-017',
    sighting_date: daysAgo(35),
    sighting_time: '13:00',
    town: 'Woodstock',
    state: 'Vermont',
    latitude: 43.6280,
    longitude: -72.5180,
    location_type: 'trail',
    bear_count: 3,
    bear_type: 'mother_with_cubs',
    behaviors: JSON.stringify(['eating', 'calm', 'climbing_tree']),
    distance_ft: 100,
    human_food_present: 0,
    pets_present: 0,
    description: 'Amazing sighting on the Appalachian Trail. Mother bear with two very small cubs. One cub climbed a birch tree while the mother foraged. Pure magic.',
    submitter_name: 'Rachel Kim',
    submitter_email: 'rkim@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-018',
    sighting_date: daysAgo(40),
    sighting_time: '18:30',
    town: 'Hyde Park',
    state: 'Vermont',
    latitude: 44.5926,
    longitude: -72.6148,
    location_type: 'farm',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['calm', 'eating']),
    distance_ft: 75,
    human_food_present: 0,
    pets_present: 1,
    description: 'Bear grazing in the lower pasture at dusk. Cattle were in the upper field and seemed aware of the bear but were not alarmed. Farm dog stayed close to the house.',
    submitter_name: 'Bill Storey',
    submitter_email: null,
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-019',
    sighting_date: daysAgo(45),
    sighting_time: '10:15',
    town: 'Warren',
    state: 'Vermont',
    latitude: 44.1115,
    longitude: -72.8578,
    location_type: 'forest',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['resting', 'calm']),
    distance_ft: 90,
    human_food_present: 0,
    pets_present: 0,
    description: 'Bear resting in a sunny patch of forest just off the Mad River Path. It was aware of me but showed no aggression. I moved on quickly.',
    submitter_name: 'Lisa Thornton',
    submitter_email: 'lthornton@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'reviewed',
    reviewed_at: new Date().toISOString(),
  },
  {
    id: 'seed-020',
    sighting_date: daysAgo(50),
    sighting_time: '19:00',
    town: 'Killington',
    state: 'Vermont',
    latitude: 43.6037,
    longitude: -72.7870,
    location_type: 'campsite',
    bear_count: 1,
    bear_type: 'adult',
    behaviors: JSON.stringify(['aggressive', 'near_trash', 'eating']),
    distance_ft: 10,
    human_food_present: 1,
    pets_present: 0,
    description: 'Bear got very close to our camp. It had clearly been conditioned to associate campsites with food. Made loud noises, bear backed off but returned twice. Reported to the campsite ranger.',
    submitter_name: 'Dave Okonkwo',
    submitter_email: 'dokonkwo@example.com',
    consent_given: 1,
    photo_filename: null,
    status: 'flagged',
    reviewed_at: new Date().toISOString(),
  },
]

const insert = db.prepare(`
  INSERT OR REPLACE INTO sightings (
    id, sighting_date, sighting_time, town, state, latitude, longitude,
    location_type, bear_count, bear_type, behaviors, distance_ft,
    human_food_present, pets_present, description,
    submitter_name, submitter_email, consent_given, photo_filename,
    status, reviewed_at
  ) VALUES (
    @id, @sighting_date, @sighting_time, @town, @state, @latitude, @longitude,
    @location_type, @bear_count, @bear_type, @behaviors, @distance_ft,
    @human_food_present, @pets_present, @description,
    @submitter_name, @submitter_email, @consent_given, @photo_filename,
    @status, @reviewed_at
  )
`)

const insertMany = db.transaction((rows: typeof seedData) => {
  for (const row of rows) {
    insert.run(row)
  }
})

insertMany(seedData)
console.log(`Seeded ${seedData.length} sample bear sightings.`)
